### ISSUE TITLE
Enabling both preload and integrity hashes causes double asset download

### ISSUE THREAD

**Issue by massimilianobraglia** [symfony/webpack-encore-bundle#101]
As you can see in the screenshots below, having both preload and integrity enabled causes issues like double asset download.
This seems to be caused by the tag renderer that does not sets the link header with the integrities.

![image](https://user-images.githubusercontent.com/17158942/101771558-6a977080-3aea-11eb-8590-2f00d2277be1.png)
![image](https://user-images.githubusercontent.com/17158942/101772242-67e94b00-3aeb-11eb-9fd7-c9a68425486e.png)

**Comment by m-vo** [comment]
I'm facing the same issue. IMHO it's web-link, that must also set `integrity="<hash>"` on the headers. 

At least when doing so, the problem disappears. :smile: 

It feels these two bundles should not rely too heavily on each other. But they probably would need to a bit if this the right way to fix the issue. Maybe @weaverryan can shed some light on this, then I'll have a go with a PR?

**Comment by alexander-schranz** [comment]
I did also stumble over this issue. I did currently workaround the following way:

```yaml
webpack_encore:
    preload: false
```

```twig
        {% set assetCss = asset('build/website/app.css') %}
        {% do preload(assetCss, { as: 'style', integrity: app_integrity('website', assetCss) }) %}

        {{ encore_entry_link_tags('app', null, 'website') }}
```

```php
<?php

namespace App\Twig;

use Symfony\WebpackEncoreBundle\Asset\EntrypointLookupCollectionInterface;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class IntegrityExtension extends AbstractExtension
{
    /**
     * @var EntrypointLookupCollectionInterface
     */
    private $entrypointLookupCollection;

    public function __construct(
        EntrypointLookupCollectionInterface $entrypointLookupCollection
    ) {
        $this->entrypointLookupCollection = $entrypointLookupCollection;
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction(
                'app_integrity',
                [$this, 'getIntegrity'],
                [
                    'is_safe' => ['html'],
                ]
            ),
        ];
    }

    public function getIntegrity(string $buildname, string $path): string
    {
        $integrityList = $this->entrypointLookupCollection->getEntrypointLookup($buildname)->getIntegrityData();

        return $integrityList[$path];
    }
}
```

**Comment by oleg-andreyev** [comment]
Faced same issue today. Initially wanted to do it manually `<link type="preload"` but then found that after using `encore_entry_css_files` or `encore_entry_js_files`, `encore_entry_script_tags` and `encore_entry_link_tags` will not return any results. Then found encore supports `preload` out-of-the-box but faced current issue.

**Comment by joanfabregat** [comment]
According to [this comment](https://stackoverflow.com/a/65500383/1839947) on Stackoverflow, both the `integrity` and `crossorigin` parameters are required on both the `Link` header and on the `<link>` tags. 

Using Symfony 6.3.2 and Encore 1.17.1 both the parameters are present on the `<link>` tags: 
![Screenshot 2023-08-16 at 19 06 00](https://github.com/symfony/webpack-encore-bundle/assets/4227907/c832ed0f-763a-430d-a9a8-90237bd493ad)

However only the crossorigin parameter is specified on the `Link` header: 
![Screenshot 2023-08-16 at 19 05 55](https://github.com/symfony/webpack-encore-bundle/assets/4227907/d78d9154-7264-44f7-9903-471145ab4fbd)

My current Encore config is: 
```yaml
webpack_encore:
    crossorigin: 'anonymous'
    preload: true
```

**Comment by hracik** [comment]
Having the same issue now with newer **symfony/webpack-encore-bundle 2.1.1** and **symfony 5.4**.
