### ISSUE TITLE
Exception when using not default output_path

### ISSUE THREAD

**Issue by zorn-v** [symfony/webpack-encore-bundle#107]
Steps to reproduce:
1. Run
```bash
composer create symfony/skeleton
cd skeleton
composer req encore twig maker doctrine/annotations
./bin/console make:cont Test
```
2. Add `{{ encore_entry_link_tags('app') }}` in `templates/base.html.twig`
3. Change `output_path` in `config/packages/webpack_encore.yaml` to `%kernel.project_dir%/public/build/default`
4. Change paths in `webpack.config.js`
```js
Encore
    // directory where compiled assets will be stored
    .setOutputPath('public/build/default')
    // public path used by the web server to access the output path
    .setPublicPath('/build/default')
```
5. Run `npm i && npm run build`
6. Run web server (e.g. `php -S 8888 -t public`) and open http://localhost:8888/test

And you get exeption like this 
`An exception has been thrown during the rendering of a template ("Asset manifest file "/var/www/html/public/build/manifest.json" does not exist.").`

**Comment by zorn-v** [comment]
Really ?
Nobody change output_path ?

**Comment by zorn-v** [comment]
You also need to change `framework.assets.json_manifest_path` config value in such case

**Comment by weaverryan** [comment]
I've added a note about this to the docs. Thanks!
