### ISSUE TITLE
Usage outside of Symfony? 

### ISSUE THREAD

**Issue by dingo-d** [symfony/webpack-encore-bundle#120]
I have a, maybe silly, question.

Is it possible, and if so, how, to use webpack-encore-bundle outside Symfony? I'd like to create a super simple github page, and though about using Twig as a template, but I needed to add some assets, so I used `@symfony/webpack-encore` in my `package.json`.

And it works perfectly as described in the docs. I also added `symfony/webpack-encore-bundle` to my `composer.json`, but I'm not sure how to expose it to twig 🙈 

When I use 

```twig
{% block stylesheets %}
    {{ encore_entry_link_tags('app') }}
{% endblock %}
```

I get the error 

> Fatal error: Uncaught Twig\Error\SyntaxError: Unknown "encore_entry_link_tags" function. in /templates/base.html.twig on line 7

Can it be loaded as an extension? Or should I just use this package: https://github.com/mehrkanal/twig-encore-extension?

**Comment by jrushlow** [comment]
The short answer would be no - the bundle itself it designed to work with Symfony. 

I'm not sure what you're trying to achieve is actually doable w/ Github Pages. GH Pages can only serve static content and is built with Jekyll as far as I know. An alternative approach would be to build a light weight Symfony App, use Github actions to build the static content, and then publish the content created by Encore to the Github Pages repo/directory.

> Or should I just use this package: https://github.com/mehrkanal/twig-encore-extension?

I have not looked through the code base, but I see they just published their first release an hour ago - buyer beware.

**Comment by dingo-d** [comment]
> An alternative approach would be to build a light weight Symfony App, use Github actions to build the static content, and then publish the content created by Encore to the Github Pages repo/directory.

That's basically what I'm aiming at 😄 

I didn't want to add too much overhead just to build a simple HTML site served on the GH pages. The idea is to build everything with Twig (I have some dynamic content I'll be fetching and displaying in the loops, which is why I opted for Twig), then use GH Actions to deploy this to the GH pages.

> I have not looked through the code base, but I see they just published their first release an hour ago - buyer beware.

They released it today after I pinged them if they could because they didn't tag it, but it actually works fine 😄
