### ISSUE TITLE
Upgrade 'css-what' to fix high severity vulnerability

### ISSUE THREAD

**Issue by webinarium** [symfony/webpack-encore-bundle#131]
The `css-what` library contains "Denial of Service" vulnerability, which has been fixed as of 5.0.1.
Could you please upgrade the webpack-encore dependencies as advised below.

**Severity**: High
**Vulnerability**: Denial of Service
**Package**: css-what
**Patched in**: >=5.0.1
**Dependency of**: @symfony/webpack-encore [dev]
**Path**: @symfony/webpack-encore > css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > css-select > css-what
**More info**: https://npmjs.com/advisories/1754

**Comment by trompette** [comment]
Dependabot created an alert on one of my project:

![image](https://user-images.githubusercontent.com/181746/122379060-cd206c00-cf66-11eb-8748-b924b1d10abe.png)

**Comment by trompette** [comment]
Maybe the issue should be created in the https://github.com/symfony/webpack-encore repository... :man_shrugging:

**Comment by webinarium** [comment]
> Maybe the issue should be created in the https://github.com/symfony/webpack-encore repository...

Good idea, thank you! I've resubmitted the issue into "symfony/webpack-encore" repository as symfony/webpack-encore#1003. Please feel free to add your dependabot screenshot there, so they are aware I'm not alone with the issue. :)

I also created issue symfony/webpack-encore#1004, in case you have the same one.
