### ISSUE TITLE
Investigate the way to render preload links easily

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore-bundle#14]
Currently, the bundle performs de-duplication of the returned files. This is useful to avoid rendering the same `<script>` tag multiple times. But it makes it harder to render `<link rel="preload">` in the `<head>` and then `<script>` at the end of the body (as here, we precisely need to get the full list twice).

The way to do it currently would be to call `encore_entry_js_files` and store the result in a variable used in both places. But this is not convenient at all. The variable must be defined in a scope higher than both places needing it, and it is very common to have a block wrapping the `<script>` tags to make it handy for child templates to add more, but blocks create a new scope and so mutating the array inside the block has no effect outside it. It is also quite fragile in case the variable name is used elsewhere in the template (as the head and the end of the body are at opposite sides of the rendering of the template).

**Comment by weaverryan** [comment]
I really want to solve this kind of stuff. As you know, there is a competing issue about this here: https://github.com/symfony/webpack-encore/issues/429 - the idea would be that we allow you to define which entries you want to set as "preload" in `webpack.config.js`, and that is communicated via this bundle back to the WebLink component so that it can add the preload via a header.

Thoughts / concerns on that approach?

**Comment by stof** [comment]
well, there is 2 separate things here. https://github.com/symfony/webpack-encore/issues/429 is about being able to preload chunks which are referenced through code splitting (according to the plugin being linked).

Here, I'm first talking about being able to preload the files of the main entrypoint at first. Opening this issue was based on a discussion with a community member (I don't remember whether it was on Slack on in the discussion on an issue), who was saying that before switching to encore 0.21 and encore-bundle, they were rendering all their script tags as deferred and at the very end of the body, while having `<link rel="preload">` in the head for all of them, so that the browser discovers them very early.
The only issue to implement this workflow with the existing API is the deduplication logic, which makes it hard to get the list of files both in the head and at the end of the body.

**Comment by weaverryan** [comment]
Ah, I didn’t intend for the other issue to be only about the async chunks, but the issue in general of how to support preload etc. it could be solved in the bundle by adding an option / function that ignores the dedup. Or in Encore itself, but configuring the behavior you want in you config (e.g. addEntry() or some other method) and have the bundle read that config to do it for you. That’s the part I’m undecided on.

**Comment by weaverryan** [comment]
See #61, to solve at least part (maybe all?) of this problem. I need validation & discussion on that approach.
