### ISSUE TITLE
Stimulus 3 support?

### ISSUE THREAD

**Issue by gremo** [symfony/webpack-encore-bundle#148]
Can't get Stimulus 3 to work. When I `.enableStimulusBridge('./assets/controllers.json')` and require latest version (currently, 3) of Stimulus, an error occurred running `yarn encore dev`. It complains about installing `stimulus`.

Is Stimulus 3 supported?

**Comment by maxhelias** [comment]
Not yet, this is on progress, see :
- https://github.com/symfony/stimulus-bridge/pull/48
- https://github.com/symfony/stimulus-testing/pull/4
- https://github.com/symfony/ux/pull/141

**Comment by gremo** [comment]
Thanks

**Comment by tgalopin** [comment]
I just merged the PR. Stimulus 3 support will be released in Symfony UX 2.0 (coming soon).

**Comment by gremo** [comment]
Thank you so much! So I will be able to use Stimulus 3 starting from a new release of webpack-encore-bundle, right?
