### ISSUE TITLE
Upgrade symfony/service-contracts dependency for Symfony 6.0

### ISSUE THREAD

**Issue by SBordier44** [symfony/webpack-encore-bundle#157]
Hi,
After Symfony 6.0 installation, we make installation of webpack-encore-bundle, and we obtain an error of dependency service-contracts not supported by current release of this bundle.

Installed with symfony 6: symfony/service-contracts:^3.0
Required by bundle (last version): symfony/service-contracts:^1.0 || ^2.0

Stacktrace of Composer:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - symfony/webpack-encore-bundle[v1.13.0, ..., v1.13.1] require symfony/service-contracts ^1.0 || ^2.0 -> found symfony/service-contracts[v1.1.1, ..., v1.1.11, v2.0.0, ..., v2.5.0] but the package is fixed to v3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires symfony/webpack-encore-bundle ^1.13 -> satisfiable by symfony/webpack-encore-bundle[v1.13.0, v1.13.1].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require symfony/webpack-encore-bundle:*" to figure out if any version is installable, or "composer require symfony/webpack-encore-bundle:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Thanks

**Comment by SBordier44** [comment]
Related MR #155

**Comment by luca-rath** [comment]
@SBordier44 #155 has been merged, so I guess this can be closed now

**Comment by SBordier44** [comment]
Good, thanks :)
