### ISSUE TITLE
"encore_entry_link_tags" & "encore_entry_script_tags" ignore the basePath (X-Forwarded-Prefix)

### ISSUE THREAD

**Issue by jcrombez** [symfony/webpack-encore-bundle#174]
When using `encore_entry_link_tags` or `encore_entry_script_tags` and changing the basePath by leveraging the X-Forwarded-Prefix header from a reverse-proxy, the asset url given by this bundle to the symfony/asset library start with "/" and because of this :

https://github.com/symfony/asset/blob/49e355b57b4b6a5cef1d2dbc4e36cee49369cf7d/PathPackage.php#L56

The assets don't get the correct url prefix and end in 404.

My (awful) workaround being :

```twig
        {% block stylesheets %}
            {{ encore_entry_link_tags('app')|replace({'href="': 'href="' ~ app.request.basePath})|raw }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app')|replace({'src="': 'src="' ~ app.request.basePath})|raw }}
        {% endblock %}
```

**Comment by weaverryan** [comment]
Hey @jcrombez!

Hmm. The first thing I would try is this: https://symfony.com/doc/current/frontend/encore/faq.html#my-app-lives-under-a-subdirectory

The idea is that the final `entrypoints.json` file would contain the TRUE final paths that your frontend needs to use (including, for example, a potential full https://... CDN URL). I'm not sure that's the ideal solution for you, but currently Encore is set up in such a way where you really need to tell IT what your subdirectory path is. If you need this to be different locally vs production, you can use environment variables in your `webpack.config.js` file.

I hope this helps!

**Comment by jcrombez** [comment]
I'm not sure it would be possible in the case of a proxy http header.
Thank you for taking the time to suggest a workaround though :)
