### ISSUE TITLE
[RFC] Allow stimulus_*() Twig functions to return arrays instead of strings

### ISSUE THREAD

**Issue by jmsche** [symfony/webpack-encore-bundle#176]
Hi,

In some cases (most being using Stimulus with Forms) it would be useful that `stimulus_*()` Twig functions return an array of attributes instead of strings, so it could be applied directly, eg.:

```twig
{{ form_row(form.type, { 'attr': stimulus_action('my_controller', 'actionName', 'change' }) }}
```

Returning an array would also allow to merge the attributes:

```twig
{{ form_row(form.type, { 'attr': stimulus_action('my-controller', 'actionName', 'change' })|merge({ 'class': 'customClass' }) }}
```

Currently we're supposed to either use `field_*()` functions or write the attributes ourself I guess:

```twig
{{ form_row(form.type, { 'attr': { 'data-action': 'change->my-controller#actionName' } }) }}
```

WDYT?

**Comment by weaverryan** [comment]
Yea, this is a rough spot - I agree. We can't just change the return from a string to an array, and it would be annoying for the other 90% of use-cases anyways. We'd need a way (e.g. a new function or something) for the user to ask for an array version. WDYT?

**Comment by Kocal** [comment]
What about using a named parameter which controls the return type: `stimulus_action('my-controller', 'actionName', 'change', as='array')` ?

**EDIT:** I've just remembered about https://github.com/symfony/webpack-encore-bundle/issues/119#issuecomment-827356762, which suggested a new parameter `as_array`

**Comment by weaverryan** [comment]
That seems like probably the best option :)
