### ISSUE TITLE
Add Twig function and filter for Stimulus Outlets integration

### ISSUE THREAD

**Issue by pbories** [symfony/webpack-encore-bundle#205]
Hello there,

The Outlets API was introduced in Stimulus [v3.2.0](https://github.com/hotwired/stimulus/releases/tag/v3.2.0).

It would be great to have a Twig function to generate the data attribute `data-[identifier]-[outlet-name]-outlet="[selector]"` in the templates, just like `stimulus_controller`, `stimulus_action` and `stimulus_target functions`.

Should I try to make a PR or is someone already working on this ?

**Comment by pbories** [comment]
I opened a PR : https://github.com/symfony/webpack-encore-bundle/pull/206

WDYT ?

**Comment by weaverryan** [comment]
Outlets added to StimulusBundle! Use the functions from that bundle instead.

Cheers!
