### ISSUE TITLE
Move Stimulus helpers to UX repository

### ISSUE THREAD

**Issue by onEXHovia** [symfony/webpack-encore-bundle#207]
👋 I do not fully know the reasons why it is located in the current repository, but this an excellent candidate for UX ecosystem by analogy Turbo and another solutions.

**Comment by weaverryan** [comment]
We actually have a separated project already - a StimulusBundle - that does this. We just need to get the "recipes" correct so that you can still get all the Stimulus controller stuff in the correct situation. So, it's coming, and you're right :)
