### ISSUE TITLE
Work with multiple Encore configurations

### ISSUE THREAD

**Issue by berrymore** [symfony/webpack-encore-bundle#30]
This #13 issue is implemented. It solves problem which happens while using multiple Encore configurations. Now it is possible to specify as much builds as we want. But it solves "multiple configurations" problem only for CSS and JS files.

I'm using `Encore.copyFiles()` to copy my static files (images, videos, etc). [Documentation](https://symfony.com/doc/current/frontend/encore/copy-files.html) says that we need to use `asset` component which uses `json_manifest_path`. And there is no option to specify multiple manifests.

So maybe it would be a nice idea to add something like `ManifestLookup` and `encore_asset` function that will resolve path to the static files for us.

```twig
{{ encore_asset('images/top.jpg', 'landing') }}
{# Will print /builds/landing/images/top.hash.jpg #}
```

**Comment by weaverryan** [comment]
There *is* a way to specify multiple `json_manifest_path` via asset packages - it's just not a well-known feature. See the comments here: https://github.com/symfony/webpack-encore-bundle/pull/17#issuecomment-454321752

I hope that helps!
