### ISSUE TITLE
encore_entry_css_files returns nothing if called multiple time

### ISSUE THREAD

**Issue by soullivaneuh** [symfony/webpack-encore-bundle#33]
I'm using this function to render PDF with inline CSS as it was suggested in https://github.com/symfony/webpack-encore-bundle/issues/16#issuecomment-455024938:

```twig
<style>{{ asset_get_content(encore_entry_css_files('pdf')) }}</style>
```

But if I call the twig `render` method multiple time (to render multiple PDFs on one command), only the first will get CSS.

For the other, the css file list is just empty.

So I tried this for test on my homepage:

```twig
{{ dump(encore_entry_css_files('pdf')) }}
{{ dump(encore_entry_css_files('pdf')) }}
{{ dump(encore_entry_css_files('pdf')) }}
```

And it confirms the issue:

![image](https://user-images.githubusercontent.com/1698357/51483746-18d08a80-1d9a-11e9-9a1e-9333192c5f77.png)

To me, it's a bug. Why this function would not return the needed files if call multiple times?

**Comment by soullivaneuh** [comment]
Ok I found why: https://github.com/symfony/webpack-encore-bundle/blob/9c89795a4577c522101206a1a88272660735257c/src/Asset/EntrypointLookup.php#L63-L66

There is certainly a reason, maybe for tag rendering?

But for that use case, it should have an option to force duplicate returns IMO.

**Comment by soullivaneuh** [comment]
The workaround to this is to inject the entrypoint lookup and reset it before each twig render call.

See my complete service:

```php
final class PdfRenderer
{
    /**
     * @var EngineInterface
     */
    private $twig;

    /**
     * @var Dompdf
     */
    private $pdf;

    /**
     * @var TranslatorInterface&LocaleAwareInterface
     */
    private $translator;

    /**
     * @var EntrypointLookupInterface
     */
    private $encoreEntrypointLookup;

    public function __construct(EngineInterface $twig, Dompdf $pdf, TranslatorInterface $translator, EntrypointLookupInterface $encoreEntrypointLookup)
    {
        Assert::isInstanceOf($translator, LocaleAwareInterface::class);
        $this->twig = $twig;
        $this->pdf = $pdf;
        $this->translator = $translator;
        $this->encoreEntrypointLookup = $encoreEntrypointLookup;
    }

    /**
     * Generates the HTML code with Twig and pushes it to the PDF generator.
     *
     * @param mixed[] $parameters
     */
    public function renderPdf(string $template, array $parameters, ?string $locale = null): string
    {
        // We have to get a new Dompdf instance to avoid this issue: https://github.com/dompdf/dompdf/issues/1056
        // We will be able to fallback to the properties once resolved and released.
        // You can test it again using the nexy:invoice:remind command. ATM, it fails generating multiple reminders.
        $pdf = new Dompdf($this->pdf->getOptions());

        $fallbackLocale = $this->translator->getLocale();

        if (null !== $locale) {
            $this->translator->setLocale($locale);
        }

        $this->encoreEntrypointLookup->reset();
        $pdf->loadHtml($this->twig->render($template, $parameters));
        $pdf->render();
        $this->translator->setLocale($fallbackLocale);

        return (string) $pdf->output();
    }
}
```

**Comment by eschultz-magix** [comment]
Same as https://github.com/symfony/webpack-encore-bundle/issues/31 and you need to wait for https://github.com/symfony/webpack-encore-bundle/pull/21 to complete.

**Comment by MrMitch** [comment]
@Soullivaneuh how did you get the `EntrypointLookupInterface` to be injected in your service ?

Only adding the parameter to the constructor throws an exception

```
Cannot autowire service "MyClass": argument "$encoreEntryPointLookup" of 
method "MyClass::__construct()" references interface 
"Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface" 
but no such service exists. 
You should maybe alias this interface to one of these existing services: 
"webpack_encore.entrypoint_lookup", "webpack_encore.entrypoint_lookup[_default]".
```

As per de recommendation in the exception message, I added an alias but that doesn't seem to work, it seems the container just tries to create a new `EntrypointLookupInterface` instance (with the wrong parameters) instead of using the existing `webpack_encore.entrypoint_lookup` service.

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface:
        alias: 'webpack_encore.entrypoint_lookup'
```

```
Type error: Argument 1 passed to 
Symfony\WebpackEncoreBundle\Asset\EntrypointLookup::__construct() 
must be of the type string, object given, called in 
<project-root>/var/cache/dev/ContainerJpxofud/getWebpackEncore_EntrypointLookupService.php
on line 12
```

How did you get this to work ?

**Comment by MrMitch** [comment]
It seems aliasing `webpack_encore.entrypoint_lookup[_default]` works and aliasing `webpack_encore.entrypoint_lookup` doesn't. (https://github.com/symfony/webpack-encore-bundle/issues/36)

So with 
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface:
        alias: 'webpack_encore.entrypoint_lookup[_default]' # this is the important line
```
The injection of `EntrypointLookupInterface` into a service works fine.

**Comment by weaverryan** [comment]
See #45 - I think `reset()` is probably what should be used for this, but autowiring should be easier.

**Comment by DennisdeBest** [comment]
Thanks !! this helped out a lot :)

**Comment by theredled** [comment]
Is it supposed to be a wanted behaviour ?

**Comment by Kocal** [comment]
Yes it is.

**Comment by theredled** [comment]
Why ?

**Comment by Kocal** [comment]
I don't know, sureley to prevent importing the same files multiples times which can lead to undesirable behaviour.
See #45, it add a `reset` method on the `EntrypointLookupInterface` and it may helps you. 

Also, it will probably be usefull to have a way to reset the entrypoint lookup directly on Twig. WDYT @weaverryan?

**Comment by theredled** [comment]
I'm sorry but I don't understand how you can be sure it's a 100% wanted behaviour without knowing the reason why ?
I mean yes, including multiple times can lead to bugs just like any mistake... But how is that useful to prevent that one mistake ? Why not an error message ?

There is probably a better reason (or it's an issue dressed as a feature)
