### ISSUE TITLE
Exception thrown when retrieving `webpack_encore.entrypoint_lookup` from container

### ISSUE THREAD

**Issue by yesdevnull** [symfony/webpack-encore-bundle#36]
### Problem
Prior to v1.1.0 it was possible to fetch `webpack_encore.entrypoint_lookup` from the container to interact with the `EntrypointLookup` class.  Now when fetching `webpack_encore.entrypoint_lookup` from the container we get the following exception:

```
FatalExceptionError
Type error: Argument 1 passed to Symfony\WebpackEncoreBundle\Asset\EntrypointLookup::__construct() must be of the type string, object given, called in /vagrant/var/cache/prod/Container3svdnsj/getWebpackEncore_EntrypointLookupService.php on line 8
```

Looking at `WebpackEncoreExtension` the following line appears to be the culprit:

```php
$container->getDefinition('webpack_encore.entrypoint_lookup')
    ->replaceArgument(0, $factories['_default']);
```

Not being very familiar with the container and the way it works I can only speculate that it's not being resolved from the container correctly and passing the object itself rather than the output path.

Calling `webpack_encore.entrypoint_lookup[_default]` works fine as a temporary workaround but it's not an ideal solution.

### Info
**PHP:** 7.1.8
`symfony/symfony`: 3.4.20
`symfony/webpack-encore-bundle`: v1.1.0

**Comment by soullivaneuh** [comment]
I have exactly the same issue, the constructor is call twice. Once with a string (the path), a second time passing... the service itself. :thinking: :taco: 

To avoid any workaround, rollback to v1.0.0 solves also the problem, unless you really need the features from v1.1.

**Comment by MrMitch** [comment]
I've opened a PR to fix this : #39

**Comment by weaverryan** [comment]
Sorry about this - it was a bug we added and missed. You should use the `webpack_encore.entrypoint_lookup_collection` service instead. We will remove the `webpack_encore.entrypoint_lookup` service. That's a BC break... but we already made a release that broke that service, so I think we should just remove it, as it's not needed anymore.

**Comment by yesdevnull** [comment]
No worries @weaverryan, thanks for the explainer.  I'll update my code accordingly :slightly_smiling_face:

**Comment by weaverryan** [comment]
By the way, in #45, there will be autowireable alias if you need to use the service directly.
