### ISSUE TITLE
Don't require assets in test environment

### ISSUE THREAD

**Issue by karser** [symfony/webpack-encore-bundle#43]
Hello,

Twig functions encore_entry_link_tags / encore_entry_script_tags throw an exception if assets are not compiled:
```
An exception has been thrown during the rendering of a template ("Could not find the entrypoints file from Webpack: the file "/var/www/app/public/build/entrypoints.json" does not exist.")
```
This behavior is annoying when it comes to functional testing. Because building assets for symfony crawler tests is a waste of time.
Currently, I'm using this workaround
```
    <head>
        {% if app.environment != 'test' %}{{ encore_entry_link_tags('app') }}{% endif %}
    </head>
    <body>
        {% if app.environment != 'test' %}{{ encore_entry_script_tags('app') }}{% endif %}
    </body>
```

It would be nice to have an option not to throw exceptions for the test environment.

**Comment by weaverryan** [comment]
Sure, this makes sense. We could add a `strict_mode` option or something that defaults to `true`, but could be set to false to simply not render assets if they are not there.

If you're interested, you can open a PR.

Cheers!

**Comment by karser** [comment]
Thanks for the feedback. I'll do that when I have free time

**Comment by axzx** [comment]
@karser 

I am looking for resolve exception
`Asset manifest file "public/build/manifest.json" does not exist.`
when I run test and I dont have directory build

Do you know how run test on github actions without yarn build?

**Comment by karser** [comment]
@axzx I'm using this script
`bin/run-tests.sh`
```
#!/usr/bin/env bash

set -e

if [[ ! -e ./public/build/manifest.json ]]; then
    mkdir -p ./public/build
    echo "{}" > ./public/build/manifest.json
fi

composer install --dev --prefer-dist --no-interaction --no-scripts --no-progress --no-suggest
vendor/bin/simple-phpunit -c ./phpunit.xml.dist
```

**Comment by daFish** [comment]
You can also define a custom `json_manifest_path` for the test-environment:
```yaml
# config/test/framework.yaml
framework:
    test: true
    session:
        storage_id: session.storage.mock_file
    assets:
        json_manifest_path: ~
```

**Comment by JohJohan** [comment]
When i have the config mentioned by @daFish i get the following error when i dont have assets installed:
```
[CRITICAL] Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Could not find the entrypoints file from Webpack: the file "/x/public/build/entrypoints.json" does not exist.")."
```

We are running `"symfony/webpack-encore-bundle": "^1.7"`

**Comment by axzx** [comment]
> When i have the config mentioned by @daFish i get the following error when i dont have assets installed:
> 
> ```
> [CRITICAL] Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Could not find the entrypoints file from Webpack: the file "/x/public/build/entrypoints.json" does not exist.")."
> ```
> 
> We are running `"symfony/webpack-encore-bundle": "^1.7"`

do you have this configuration?
```
webpack_encore:
    strict_mode: false
```

**Comment by JohJohan** [comment]
Thanks @axzx that was it!

**Comment by axzx** [comment]
thanks @daFish :)
