### ISSUE TITLE
Could not find the entry "dummy"...  Found: entrypoints.

### ISSUE THREAD

**Issue by DiceWithSpades** [symfony/webpack-encore-bundle#47]
After update I've got:
```
[Symfony\WebpackEncoreBundle\Exception\EntrypointNotFoundException]                               
Could not find the entry "dummy" in "/source/public/build/entrypoints.json". Found: entrypoints.
```

There is indeed catch for `EntrypointNotFoundException` in `EntrypointCacheWarmer` but it refers to `ymfony\WebpackEncoreBundle\CacheWarmer\EntrypointNotFoundException` which does not exist (or my IDE is wrong) but `Symfony\WebpackEncoreBundle\Exception\EntrypointNotFoundException` exist and is thrown. I assume that `use` is missing.

EDIT:
I tested it on fresh install and problem exist there too.

**Comment by nyroDev** [comment]
Same problem here after upgrading from 1.1.0 to 1.2.0

**Comment by Amunak** [comment]
Can confirm; adding `use Symfony\WebpackEncoreBundle\Exception\EntrypointNotFoundException;` to `\Symfony\WebpackEncoreBundle\CacheWarmer\EntrypointCacheWarmer` fixes this for the time being.

**Comment by gdbonino** [comment]
Same problem

**Comment by DiceWithSpades** [comment]
I'm not entirely sure is this the right way to fix it but it's probably the easiest one. I made PR just in case (I needed to fix this in my project anyway).

**Comment by pounard** [comment]
Same happened to me today, and @Amunak proposed fix do fix the issue.

**Comment by alegout** [comment]
thanks @Amunak

**Comment by fabgg** [comment]
Thanks @Amunak, his solution works fine for me

**Comment by kalimerre** [comment]
Same for me :)

**Comment by ThePeterMick** [comment]
Same here, deleting the `public/build` contents and re-running seems to let `composer update `succeed...

**Comment by raress96** [comment]
Any updates when a new version will be available?I can not do automatic deployment for an app of mine until this is fixed.

**Comment by weaverryan** [comment]
Just merged and released the patch fix. Sorry about that! We clearly need an integration test for this layer.

Thanks!

**Comment by iluuu1994** [comment]
@weaverryan Consider [PHPStan](https://github.com/phpstan/phpstan) to avoid issues like this? Unless you have 100% coverage things like this can always slip through.
