### ISSUE TITLE
Composer require did not update existing config files

### ISSUE THREAD

**Issue by BenMorel** [symfony/webpack-encore-bundle#79]
I just added `webpack-encore-bundle` to an existing Symfony 4 project using:

```
$ composer require symfony/webpack-encore-bundle
$ yarn install
```

The following files have been created alright:

- assets/css/app.css
- assets/js/app.js
- config/packages/assets.yaml
- config/packages/prod/webpack_encore.yaml
- config/packages/webpack_encore.yaml
- package.json
- webpack.config.js
- yarn.lock

However, to my surprise, the following files have *not* been updated:

- `.gitignore` does not contain the usual exclusions like node_modules, public/build, etc.
- `config/bundles.php` does not contain the `WebpackEncoreBundle` entry

I did the same setup on another existing project a few weeks ago, and the files had been correctly updated.

**Comment by weaverryan** [comment]
Sorry for never getting to this :). I have no idea why this would have happened, but it would be a Symfony Flex issue - as this bundle just uses its recipe system. If you do see this issue again, definitely open an issue there.

Cheers!
